//
//  MultiEnvironmentApp.swift
//  MultiEnvironmentApp
//
//  Entry point. The SecureKeys xcframework linked here is generated by
//  `secure-keys env generate <environment>` and placed in
//  .secure-keys/<environment>/SecureKeys.xcframework.
//
//  To switch environments, regenerate the framework for the desired target and
//  re-link it in the Xcode project settings.
//

import SwiftUI

@main
struct MultiEnvironmentApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
