name: Run linter

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:
    inputs:
      runs-on:
        description: Runs on the specified Github runner
        required: false
        type: string

jobs:
  run-linter:
    runs-on: ${{ inputs.runs-on || vars.RUNS_ON || 'macos-latest' }}

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: bundle install

      - name: Run linter
        run: bundle exec rubocop
